server:
  port: 8080
  servlet:
    context-path: /accenture
  address: 0.0.0.0

spring:
  application:
    name: MsAccenture
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jsonplaceholder:
    url: https://jsonplaceholder.typicode.com
    name: jsonpalceholder